version: "3.8"

volumes:
  interview-node-modules:
    name: "interview-node-modules"
    external: false

services:
  movie-interview-app:
    container_name: movie-interview-app
    env_file: .env
    build:
      context: .
      dockerfile: dockerfile
      args:
          - NODE_ENV=production
          - APP_STAGE=${APP_STAGE}
    command: serve -s dist -p 3001
    ports:
      - "3001:3001"
    volumes:
      - interview-node-modules:/app/node_modules


